# Generated by Django 4.1 on 2023-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0001_add_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
